apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bluecompute-web-trigger
spec:
  params:
  - name: gitUrl
    value: $(body.repository.clone_url)
  - name: gitRevision
    value: $(body.pull_request.head.sha)
