apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bluecompute-web-build-task
spec:
  params:
    - name: BUILDER_IMAGE
      description: The location of the buildah builder image.
      default: "quay.io/buildah/stable:v1.12.0"
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile.redhat
    - name: CONTEXT
      description: Path to the directory to use as context.
      default: .
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "true"
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: overlay
  resources:
    inputs:
      - name: git-source-web
        type: git
      - name: docker-image-web
        type: image
  steps:
  - name: lint-docker-image
    image: hadolint/hadolint:latest-debian
    workingDir: /workspace/git-source-web
    command:
    - hadolint
    - --version
    - hadolint
    - $(params.DOCKERFILE)
  - name: write-to-workspace
    image: ubuntu
    workingDir: /workspace/git-source-web
    script: |
      #!/usr/bin/env bash
      SHORT_GIT_HASH="$(cat .git/FETCH_HEAD | awk '{print substr($1,0,7)}')"
      NEW_IMAGE_ID="$(resources.inputs.docker-image-web.url):$SHORT_GIT_HASH"
      echo $NEW_IMAGE_ID > /workspace/git-source-web/NEW_IMAGE_ID
  - name: build-push
    image: $(params.BUILDER_IMAGE)
    workingDir: /workspace/git-source-web
    script: |
      #!/usr/bin/env bash
      export NEW_IMAGE_ID=$(cat /workspace/git-source-web/NEW_IMAGE_ID)
      echo "Building Image $NEW_IMAGE_ID"
      buildah bud --tls-verify="$(params.TLSVERIFY)" --layers --storage-driver=$(params.STORAGE_DRIVER) -f "$(params.DOCKERFILE)" -t "$NEW_IMAGE_ID" "$(params.CONTEXT)"
      echo "Pushing Image $NEW_IMAGE_ID"
      # Adding trivy instruction here is not working
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
      echo "Vulnerability scan for the project filesystem"
      trivy fs /workspace/git-source-web
      trivy fs --clear-cache --ignore-unfixed --exit-code 0 --severity HIGH --no-progress $NEW_IMAGE_ID
      trivy fs --clear-cache --ignore-unfixed --exit-code 1 --severity CRITICAL --no-progress $NEW_IMAGE_ID
      buildah --storage-driver=$(params.STORAGE_DRIVER) push --tls-verify="$(params.TLSVERIFY)" "$NEW_IMAGE_ID" "docker://$NEW_IMAGE_ID"
      echo "Vulnerability scan for the pushed image - $NEW_IMAGE_ID"
      trivy $NEW_IMAGE_ID
      trivy --clear-cache --ignore-unfixed --exit-code 0 --severity HIGH --no-progress $NEW_IMAGE_ID
      trivy --clear-cache --ignore-unfixed --exit-code 1 --severity CRITICAL --no-progress $NEW_IMAGE_ID
    securityContext:
      privileged: true
    volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
